app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('backend.urls',namespace='app'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/urls.py
from django.urls import path, include
from . import views

app_name = "app"

urlpatterns = [
    path('', views.index, name='index'),
    path('predict/dashboard/', views.dashboard, name='dashboard'),
    path('predict/form', views.predict, name='predict'),
    path('predict/', views.predict_chances, name='submit_prediction'),
    path('user/signin/', views.sign_in_user, name='signin'),
    path('user/signup/', views.sign_up_user, name='signup'),
    # path('predict/chart/', views.data_chart, name='chart'),
    path('predict/profile/', views.profile, name='profile'),
    path('logout_user/', views.logout_user, name="logout"),
    # path('user_settings/', views.user_theme, name='user_settings'),
    # path('update_theme/', views.update_theme, name='update_theme')

]

backend/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg',
                              upload_to='profile_pict_user')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            size_output = (300, 300)
            img.thumbnail(size_output)
            img.save(self.image.path)


class PredResults(models.Model):
    fixed_acidity = models.FloatField()
    volatile_acidity = models.FloatField()
    citric_acid = models.FloatField()
    residual_sugar = models.FloatField()
    chlorides = models.FloatField()
    free_sulfur_dioxide = models.FloatField()
    total_sulfur_dioxide = models.FloatField()
    density = models.FloatField()
    pH = models.FloatField()
    sulphates = models.FloatField()
    alcohol = models.FloatField()
    classification = models.CharField(max_length=30)

    def __str__(self):
        return self.classification

backend/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from .models import *
from .validators import validate_email_unique


class form_user_create(UserCreationForm):
    username = forms.CharField(max_length=100, required=True)
    email = forms.CharField(required=True, label='Email adress', validators=[
                            validate_email_unique])
    password1 = forms.CharField(required=True, label='Password')
    password2 = forms.CharField(required=True, label='Password confirmation')

    class Meta:
        model = User
        fields = [
            'username', 'email', 'password1', 'password2'
        ]

    username.widget = forms.TextInput(
        attrs={'class': 'signupForm', 'placeholder': 'Enter your username.'})
    email.widget = forms.EmailInput(
        attrs={'class': 'signupForm', 'placeholder': 'Enter your valid email addres.', 'data-placement': 'top', 'data-content': 'Must be a valid e-mail address'})
    password1.widget = forms.PasswordInput(
        attrs={'class': 'signupForm', 'placeholder': '●●●●●●●●', 'data-placement': 'bottom'})
    password2.widget = forms.PasswordInput(
        attrs={'class': 'signupForm', 'placeholder': '●●●●●●●●'})


class form_user_update(forms.ModelForm):
    username = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email']


class user_update_profile(forms.ModelForm):
    image = forms.ImageField()

    class Meta:
        model = Profile
        fields = ['image']
    image.widget = forms.FileInput(attrs={'class': 'image-upload'})

backend/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import pandas as pd
from .models import *
import joblib
from .forms import form_user_create, form_user_update,user_update_profile
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import datetime
import json
# from .serializers import user_serializer


def index(request):
    current_user = request.user
    if current_user.is_authenticated:
        return redirect('app:dashboard')
    return render(request, 'index.html')


def sign_up_user(request):
    current_user = request.user
    if current_user.is_authenticated:
        return redirect('app:dashboard')
    form = form_user_create()
    if request.method == 'POST':
        form = form_user_create(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account was created for {username}')
            return redirect('app:signin')
    context = {
        'form': form
    }
    return render(request, 'account/signup.html', context)


def sign_in_user(request):
    current_user = request.user
    if current_user.is_authenticated:
        return redirect('app:dashboard')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            username = User.objects.get(email=username).username
        except:
            pass
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('app:dashboard')
        else:
            messages.error(request, "Username or password is invalid ")
    context = {}
    return render(request, 'account/signin.html')

@login_required(login_url='app:signin')
def profile(request):
    if request.method == 'POST':
        user_form = form_user_update(request.POST, instance=request.user)
        image_form = user_update_profile(
            request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and image_form.is_valid():
            user_form.save()
            image_form.save()
            messages.success(request, f'Your profile was updated successfully')
            return redirect('app:profile')
    else:
        user_form = form_user_update(instance=request.user)
        image_form = user_update_profile(instance=request.user.profile)
    context = {
        'user_form': user_form,
        'image_form': image_form
    }

    return render(request, 'account/profile.html', context)

def logout_user(request):
    logout(request)
    messages.success(request, "You have successfully logged out!")
    return redirect('app:signin')

@login_required(login_url='app:signin')
def dashboard(request):
    return render(request, "dashboard.html")


@login_required(login_url='app:signin')
def predict(request):
    return render(request, 'forms.html')

def predict_chances(request):

    if request.POST.get('action') == 'POST':

        fixed_acidity = float(request.POST.get('fixed_acidity'))
        volatile_acidity = float(request.POST.get('volatile_acidity'))
        citric_acid = float(request.POST.get('citric_acid'))
        residual_sugar = float(request.POST.get('residual_sugar'))
        chlorides = float(request.POST.get('chlorides'))
        free_sulfur_dioxide = float(request.POST.get('free_sulfur_dioxide'))
        total_sulfur_dioxide = float(request.POST.get('total_sulfur_dioxide'))
        density = float(request.POST.get('density'))
        pH = float(request.POST.get('pH'))
        sulphates = float(request.POST.get('sulphates'))
        alcohol = float(request.POST.get('alcohol'))

        model = pd.read_pickle(
            r"F:\Django_Project\Python3.8\app\model\wine.pickle")

        result = model.predict(
            [[fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides, free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol]])

        classification = result[0]

        PredResults.objects.create(fixed_acidity=fixed_acidity, volatile_acidity=volatile_acidity, citric_acid=citric_acid,
                                   residual_sugar=residual_sugar, chlorides=chlorides, free_sulfur_dioxide=free_sulfur_dioxide, total_sulfur_dioxide=total_sulfur_dioxide, density=density, pH=pH, sulphates=sulphates, alcohol=alcohol, classification=classification)

        return JsonResponse({'result': classification, 'fixed_acidity': fixed_acidity, 'volatile_acidity': volatile_acidity, 'citric_acid': citric_acid, 'residual_sugar': residual_sugar, 'chlorides': chlorides, 'free_sulfur_dioxide': free_sulfur_dioxide, 'total_sulfur_dioxide': total_sulfur_dioxide, 'density': density, 'pH': pH, 'sulphates': sulphates, 'alcohol': alcohol}, safe=False)

backend/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    {% include "snippets/styles.html" %}
    <style>
        *,
        *:focus,
        *:hover {
            outline: none;
        }
    </style>
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar -->
        <nav id="sidebar" class="shadow-sm">
            <div class="sidebar-header">
                <img class="mr-2" src="{% static "img/ico.ico" %}" alt="">
                Dashboard

            </div>
            <ul class="list-unstyled components">
                <li class="active">
                    <a href="{% url 'app:dashboard' %}"><i class="fas fa-home"></i>Home</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-table"></i>Results</a>
                </li>
                <li>
                    <a href="{% url 'app:predict' %}"><i class="fab fa-wpforms"></i>Forms</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-chart-bar"></i>Chart</a>
                </li>
                <li>
                    <a href="{% url 'app:profile' %}"><i class="fas fa-user icon-user"></i>Account</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-tools"></i>Tools</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-file-alt"></i>Data</a>
                </li>
                <li>
                    <a href="#themeMenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i
                            class="fas fa-palette"></i>Theme</a>
                    <ul class="collapse list-unstyled" id="themeMenu">
                        <li>
                            <div class="custom-control custom-switch ml-5">
                                <input type="checkbox" class="custom-control-input" id="darkSwitch" />
                                <label class="custom-control-label" for="darkSwitch">Dark Mode</label>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="content">
            <nav class="navbar navbar-expand-sm navbar-light bg-light shadow-sm">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="btn btn-light btn-sidebar mr-3">
                        <i class="fas fa-bars"></i>
                    </button>
                    <ul class="nav myNavbar navbar-expand-sm navbar-nav ml-auto">
                        <li class="nav-item">
                            <div class="dropdown avatar">
                                <button class="btn btn-profile dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Hello, {{ request.user.username }}<img src="{{ user.profile.image.url }}"
                                        class="profil_pict rounded-circle mr-4 ml-2" alt="">
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="{% url 'app:profile' %}"><i
                                            class="far fa-id-card mr-3"></i>Profile</a>

                                    <a class="dropdown-item" href="{% url 'app:logout' %}"><i
                                            class="fas fa-sign-out-alt mr-3"></i>Log out</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>

            </nav>
            <div class="block-content">
                <div class="container menu-content">
                    <div class="row mt-4 ">
                        <div class="col-sm card-item shadow mr-1">
                            <div class="row">
                                <div class="circle"></div>
                                <div class="circle2"></div>
                                <div class="col">
                                    <h5 class="text-card-item">Statistic Data</h5>
                                </div>
                            </div>
                            <img class="img-fluid" src="{% static "img/bar-chart.svg" %}">

                        </div>
                        <div class="col-sm card-item2 mr-1">
                            <div class="row">
                                <div class="circle"></div>
                                <div class="circle2"></div>
                                <div class="col">
                                    <h5 class="text-card-item">Analysis Data</h5>
                                </div>
                            </div>
                            <img class="img-fluid" src="{% static "img/pie-chart.svg" %}">
                            <button class="btn btn-sm btn-light mt-5 float-right">Process</button>
                        </div>
                        <div class="col-sm card-item3">
                            <div class="row">
                                <div class="circle"></div>
                                <div class="circle2"></div>
                                <div class="col">
                                    <h5 class="text-card-item">Report Data</h5>
                                </div>
                            </div>
                            <img class="img-fluid" src="{% static "img/report.svg" %}">
                            <button class="btn btn-sm btn-light mt-5 float-right">Look report</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="myCard  mr-3 col-sm-7 mt-4">
                            <div class="form-inline">
                                <button class="btn btn-info mb-4 mr-3"><i class="fas fa-plus-square"></i> Add
                                </button>
                                <button class="btn myBtn2 mb-4 mr-3"><i class="fas fa-trash-alt"></i></button>
                                <button class="btn myBtn2 mb-4"><i class="fas fa-backspace"></i></button>
                            </div>
                            <canvas id="chart-algorithm" height="300" width="300"></canvas>
                        </div>
                        <div class=" col-sm myCard h-50 calendar mt-4">
                            <div class="card-calendar">
                                <div class="row main-year">
                                    <div class="col year_month">
                                        <h5 class="month font-weight-bold mt-2" id="monthAndYear"></h5>
                                    </div>
                                    <div class="col-5 button-change">
                                        <div class="float-right">
                                            <button class="btn btn-calendar" id="previous" onclick="previous()"><i
                                                    class="fas fa-chevron-left"></i></button>
                                            <button class="btn  btn-calendar" id="next" onclick="next()"><i
                                                    class="fas fa-chevron-right"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="content-card">
                                <div class="container-calendar">
                                    <table class=" table table-borderless" id="calendar" data-lang="en">
                                        <thead id="thead-month"></thead>
                                        <tbody id="calendar-body"></tbody>
                                    </table>
                                    <div class="footer-container-calendar">
                                        <label for="month">Jump To: </label>
                                        <select id="month" onchange="jump()">
                                            <option value=0>Jan</option>
                                            <option value=1>Feb</option>
                                            <option value=2>Mar</option>
                                            <option value=3>Apr</option>
                                            <option value=4>May</option>
                                            <option value=5>Jun</option>
                                            <option value=6>Jul</option>
                                            <option value=7>Aug</option>
                                            <option value=8>Sep</option>
                                            <option value=9>Oct</option>
                                            <option value=10>Nov</option>
                                            <option value=11>Dec</option>
                                        </select>
                                        <select id="year" onchange="jump()"></select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% include "snippets/scripts.html" %}

</html>

backend/templates/forms.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form</title>
    {% include "snippets/styles.html" %}
    <style>
        *,
        *:focus,
        *:hover {
            outline: none;
        }
    </style>
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar -->
        <nav id="sidebar" class="shadow">
            <div class="sidebar-header">
                <img class="mr-2" src="{% static "img/ico.ico" %}" alt="">
                Dashboard
            </div>
            <ul class="list-unstyled components">
                <li>
                    <a href="{% url 'app:dashboard' %}"><i class="fas fa-home"></i>Home</a>

                </li>
                <li>
                    <a href="#"><i class="fas fa-table"></i>Results</a>
                </li>
                <li class="active">
                    <a href="{% url 'app:predict' %}"><i class="fab fa-wpforms"></i>Forms</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-chart-bar"></i>Chart</a>
                </li>
                <li>
                    <a href="{% url 'app:profile'%}"><i class="fas fa-user icon-user"></i>Account</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-tools"></i>Tools</a>
                </li>
                <li>
                    <a href="#"><i class="fas fa-file-alt"></i>Data</a>
                </li>
                <li>
                    <a href="#themeMenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i
                            class="fas fa-palette"></i>Display</a>
                    <ul class="collapse list-unstyled" id="themeMenu">
                        <li>
                            <div class="custom-control custom-switch ml-5">
                                <input type="checkbox" class="custom-control-input" id="darkSwitch" />
                                <label class="custom-control-label" for="darkSwitch">Dark Mode</label>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="content">
            <nav class="navbar navbar-expand-sm navbar-light bg-light shadow">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="btn btn-light btn-sidebar mr-3">
                        <i class="fas fa-bars"></i>
                    </button>
                    <button class="btn avatar-btn d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item">
                                <div class="dropdown avatar">
                                    <button class="btn btn-profile dropdown-toggle" type="button"
                                        id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                        Hello, {{ request.user.username }}<img src="{{user.profile.image.url}}"
                                            class="profil_pict rounded-circle mr-4 ml-2" alt="">
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{% url 'app:profile' %}"><i
                                                class="far fa-id-card mr-3"></i>Profile</a>
                                        <a class="dropdown-item" href="{% url 'app:logout' %}"><i
                                                class="fas fa-sign-out-alt mr-3"></i>Log out</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="block-content">
                <div class="container mt-3">
                    <div class="row">
                        <div class="col-md-5 myCard shadow mr-2">
                            <h1 class="heading-form">Form Variable</h1>
                            <form action="" id="post-form" autocomplete="off">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-6">
                                        <label for="sepal_length">Fixed acidity</label>
                                        <input type="number" step="0.1" class="form-control" id="fixed_acidity"
                                            placeholder="" required>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="Sepal Width">Volatile acidity</label>
                                        <input type="number" step="0.1" class="form-control" id="volatile_acidity"
                                            placeholder="" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6">
                                        <label for="petal_length">Critic acid</label>
                                        <input type="number" step="0.1" class="form-control" id="citric_acid"
                                            placeholder="" required>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="petal_width">Residual sugar</label>
                                        <input type="number" step="0.1" class="form-control" id="residual_sugar"
                                            placeholder="" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6">
                                        <label for="petal_width">Chlorides</label>
                                        <input type="number" step="0.1" class="form-control" id="chlorides"
                                            placeholder="" required>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="petal_width">Free sulfur dioxide</label>
                                        <input type="number" step="0.1" class="form-control" id="free_sulfur_dioxide"
                                            placeholder="" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6">
                                        <label for="petal_width">Total sulfur dioxide</label>
                                        <input type="number" step="0.1" class="form-control" id="total_sulfur_dioxide"
                                            placeholder="" required>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="petal_width">Density</label>
                                        <input type="number" step="0.1" class="form-control" id="density" placeholder=""
                                            required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6">
                                        <label for="petal_width">pH</label>
                                        <input type="number" step="0.1" class="form-control" id="pH" placeholder=""
                                            required>
                                    </div>
                                    <div class="col-sm-6">
                                        <label for="petal_width">Sulphates</label>
                                        <input type="number" step="0.1" class="form-control" id="sulphates"
                                            placeholder="" required>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm">
                                        <label for="petal_width">Alcohol</label>
                                        <input type="number" step="0.1" class="form-control" id="alcohol" placeholder=""
                                            required>
                                    </div>
                                </div>
                                <button id="process" type="submit" value="Submit"
                                    class="btn myBtn btn-block">Submit</button>
                            </form>
                        </div>
                        <div class="col">
                            <div class="my-chart mt-2 myCard shadow">
                                <canvas id="myChart"></canvas>
                            </div>
                            <div class="my-table myCard mt-3 shadow">
                                <h3 class="heading-form">Variable Input</h3>
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th class="col-var" scope="col">Fixed acidity</th>
                                                <th class="col-var" scope="col">Volatile acidity</th>
                                                <th class="col-var" scope="col">Critic acid</th>
                                                <th class="col-var" scope="col">Residual sugar</th>
                                                <th class="col-var" scope="col">Chlorides</th>
                                                <th class="col-var" scope="col">Free sulfur</th>
                                                <th class="col-var" scope="col">Total sulfur</th>
                                                <th class="col-var" scope="col">Density</th>
                                                <th class="col-var" scope="col">pH</th>
                                                <th class="col-var" scope="col">Sulphates</th>
                                                <th class="col-var" scope="col">Alcohol</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td class"var-wine"><span id="fa"></span></td>
                                                <td><span id="va"></span></td>
                                                <td><span id="ca"></span></td>
                                                <td><span id="rs"></span></td>
                                                <td><span id="c"></span></td>
                                                <td><span id="fsd"></span></td>
                                                <td><span id="tsd"></span></td>
                                                <td><span id="d"></span></td>
                                                <td><span id="ph"></span></td>
                                                <td><span id="s"></span></td>
                                                <td><span id="a"></span></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <h5 class="heading-form mt-5">Prediction Classification : <span id="prediction"></span>
                                </h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</body>
{% include "snippets/scripts.html" %}

</html>

</html>